apiVersion: v1
kind: Secret
metadata:
  name: secret-config
  namespace: default
data:
  NAVER_MAPS_CLIENT_ID: YXV3dWR0ZXpvMwo=
  NAVER_MAPS_CLIENT_TOKEN: RERuNFdlTGo0UlcwOTFlM2ZwZkVmaXRGdEkxcVJpcUY2UTNJRTBZVAo=
