apiVersion: v1
kind: Secret
metadata:
  name: secret-config
  namespace: default
data:
  naver-maps-client-id: YXV3dWR0ZXpvMw==
  naver-maps-client-token: RERuNFdlTGo0UlcwOTFlM2ZwZkVmaXRGdEkxcVJpcUY2UTNJRTBZVA==
