server:
  port: 8080

spring:
  application:
    name: move
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: move
#<<< EDA / Topic Name
          destination: alpcaproject
#>>> EDA / Topic Name
          contentType: application/json
        event-out:
#<<< EDA / Topic Name
          destination: alpcaproject
#>>> EDA / Topic Name
          contentType: application/json
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:move
      username: sa
      password:
  datasource:
    generate-unique-name: false
logging:
  level:
    org.hibernate.type: info
    org.springframework.cloud: info

naver-maps:
  url: https://naveropenapi.apigw.ntruss.com/map-direction-15/v1/driving
  client-id: auwudtezo3
  client-token: DDn4WeLj4RW091e3fpfEfitFtI1qRiqF6Q3IE0YT

server:
  port: 8083

---

spring:
  profiles: docker
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: move
          destination: alpcaproject
          contentType: application/json
        event-out:
          destination: alpcaproject
          contentType: application/json
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:move
      username: sa
      password:
  datasource:
    generate-unique-name: false
naver-maps:
  url: https://naveropenapi.apigw.ntruss.com/map-direction-15/v1/driving
  client-id: ${NAVER_MAPS_CLIENT_ID}
  client-token: ${NAVER_MAPS_CLIENT_TOKEN}