apiVersion: apps/v1
kind: Deployment
metadata:
  name: moveview
  labels:
    app: moveview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moveview
  template:
    metadata:
      labels:
        app: moveview
    spec:
      containers:
        - name: moveview
          image: "username/moveview:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
