apiVersion: apps/v1
kind: Deployment
metadata:
  name: move
  labels:
    app: move
spec:
  replicas: 1
  selector:
    matchLabels:
      app: move
  template:
    metadata:
      labels:
        app: move
    spec:
      containers:
        - name: move
          image: "gmlwlswldbs/move:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          env:
          - name: secret-config
            valueFrom:
              secretKeyRef:
                name: NAVER_MAPS_CLIENT_ID
                key: NAVER_MAPS_CLIENT_ID
          - name: secret-config
            valueFrom:
              secretKeyRef:
                name: NAVER_MAPS_CLIENT_TOKEN
                key: NAVER_MAPS_CLIENT_TOKEN
