server:
  port: 8080

spring:
  application:
    name: location
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: location
#<<< EDA / Topic Name
          destination: alpcaproject
#>>> EDA / Topic Name
          contentType: application/json
        event-out:
#<<< EDA / Topic Name
          destination: alpcaproject
#>>> EDA / Topic Name
          contentType: application/json
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:location
      username: sa
      password:
  datasource:
    generate-unique-name: false
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug


server:
  port: 8086

---

spring:
  profiles: docker
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: location
          destination: alpcaproject
          contentType: application/json
        event-out:
          destination: alpcaproject
          contentType: application/json
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:location
      username: sa
      password:
  datasource:
    generate-unique-name: false


