apiVersion: apps/v1
kind: Deployment
metadata:
  name: family
  labels:
    app: family
spec:
  replicas: 1
  selector:
    matchLabels:
      app: family
  template:
    metadata:
      labels:
        app: family
    spec:
      containers:
        - name: family
          image: "username/family:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
